# Generated by Django 6.0.1 on 2026-01-10 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('descrizione', models.CharField(blank=True, max_length=255)),
                ('reparto', models.CharField(blank=True, max_length=10, null=True)),
                ('cat_stat', models.CharField(blank=True, max_length=10, null=True)),
                ('tmc_giorni', models.IntegerField(default=30, help_text='Giorni di vita (TMC)')),
            ],
        ),
        migrations.CreateModel(
            name='LottoVirtuale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_arrivo', models.DateField()),
                ('qta_iniziale', models.DecimalField(decimal_places=3, max_digits=10)),
                ('qta_residua', models.DecimalField(decimal_places=3, max_digits=10)),
                ('data_scadenza_stimata', models.DateField()),
                ('data_scadenza_reale', models.DateField(blank=True, null=True)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotti', to='inventory.prodotto')),
            ],
        ),
    ]
