# Generated by Django 6.0.1 on 2026-02-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='pezzi_per_cartone',
            field=models.IntegerField(default=1, verbose_name='Pz x Cartone'),
        ),
    ]
