# Generated by Django 6.0.1 on 2026-02-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_prodotto_pezzi_per_cartone'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='giacenza',
            field=models.IntegerField(default=0, verbose_name='Giacenza Attuale'),
        ),
    ]
