"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&d1e96#$6&%%00oe*9sin2c812@-$mip0z)048r@a8=v&5e9aq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'inventory',
    'sales',
    'scanner',
    'orders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Aumentiamo il limite dei campi per i fornitori con molti prodotti
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# --- FOGLIO GOOGLE PER PAGINA CASSE (tabella veloce via CSV, colonne A–F) ---
# Usa l’ID del foglio dall’URL di MODIFICA (apri il foglio → nella barra indirizzi vedi
# .../d/QUESTO_È_L_ID/edit#gid=...). NON usare l’URL “Pubblica sul web” (/d/e/...).
# Condivisione: “Chiunque con il link può visualizzare”.
# Lascia vuoto SPREADSHEET_ID se usi GOOGLE_SHEET_CASSE_CSV_URL (URL completo).
GOOGLE_SHEET_CASSE_SPREADSHEET_ID = os.environ.get(
    'GOOGLE_SHEET_CASSE_SPREADSHEET_ID',
    '1LpRF63GTmyU_EI3VzsDst1_-9InAofk-ZDbcFKPY-hI'
)
GOOGLE_SHEET_CASSE_GID = os.environ.get('GOOGLE_SHEET_CASSE_GID', '1527681967')
# Oppure imposta direttamente l’URL di export (es. se l’ID non funziona):
GOOGLE_SHEET_CASSE_CSV_URL = os.environ.get('GOOGLE_SHEET_CASSE_CSV_URL', '')
CASSE_TABLE_CACHE_SECONDS = 180  # 3 minuti (usato solo se non c'è file locale)
# File locale aggiornato da Google (Apps Script): se esiste, la pagina casse lo usa = caricamento istantaneo
CASSE_LOCAL_CSV_PATH = BASE_DIR / 'csv_temp' / 'saldi_casse.csv'
# Chiave per l'endpoint POST da Google: imposta in variabile d'ambiente CASSE_UPDATE_SECRET (es. una stringa lunga casuale)
CASSE_UPDATE_SECRET = os.environ.get('CASSE_UPDATE_SECRET', '')

# --- CONFIGURAZIONE EMAIL ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'fconigliaro@supermercaticonigliaro.it'
EMAIL_HOST_PASSWORD = 'jidrvtmjcjbvijds' 
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER