# Generated by Django 6.0.1 on 2026-02-03 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_prodotto_giacenza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('attivo', models.BooleanField(default=True, verbose_name='Fornitore Attivo')),
                ('email_ordini', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('indirizzo', models.TextField(blank=True, null=True)),
                ('giorno_consegna_abituale', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fornitori',
            },
        ),
        migrations.CreateModel(
            name='OrdineFornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('stato', models.CharField(choices=[('BOZZA', 'Bozza'), ('INVIATO', 'Inviato'), ('CONFERMATO', 'Confermato')], default='BOZZA', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.fornitore')),
            ],
            options={
                'verbose_name_plural': 'Ordini Fornitori',
            },
        ),
        migrations.CreateModel(
            name='RigaOrdine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pezzi_per_collo', models.IntegerField(default=1)),
                ('qta_1', models.IntegerField(default=0, verbose_name='Qta')),
                ('unita_1', models.CharField(choices=[('COLLI', 'Colli'), ('PEZZI', 'Pezzi'), ('EXPO', 'Expo'), ('KG', 'Kg')], default='COLLI', max_length=10, verbose_name='U.M.')),
                ('qta_2', models.IntegerField(blank=True, default=0, null=True, verbose_name='Qta Extra')),
                ('unita_2', models.CharField(blank=True, choices=[('COLLI', 'Colli'), ('PEZZI', 'Pezzi'), ('EXPO', 'Expo'), ('KG', 'Kg')], default='PEZZI', max_length=10, null=True, verbose_name='U.M. Extra')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='orders.ordinefornitore')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.prodotto')),
            ],
            options={
                'verbose_name_plural': 'Righe Ordine',
            },
        ),
        migrations.CreateModel(
            name='ListinoFornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_articolo_fornitore', models.CharField(blank=True, max_length=50, null=True)),
                ('prezzo_acquisto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('escludi_da_ordine', models.BooleanField(default=False, verbose_name='🚫 Escludi (Obsoleto)')),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti_listino', to='orders.fornitore')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.prodotto')),
            ],
            options={
                'unique_together': {('fornitore', 'prodotto')},
            },
        ),
    ]
