# Generated by Django 6.0.1 on 2026-02-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rigaordine',
            name='qta_2',
        ),
        migrations.RemoveField(
            model_name='rigaordine',
            name='unita_2',
        ),
        migrations.AlterField(
            model_name='rigaordine',
            name='qta_1',
            field=models.IntegerField(default=0, verbose_name='Quantità'),
        ),
    ]
