# Generated by Django 6.0.1 on 2026-02-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_rigaordine_qta_2_remove_rigaordine_unita_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornitore',
            name='codice',
            field=models.CharField(blank=True, help_text='Es. 23 per Barilla Bakery, 8314 per Barilla Primi', max_length=50, null=True, verbose_name='Codice fornitore'),
        ),
    ]
