# Generated by Django 6.0.1 on 2026-02-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_fornitore_codice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornitore',
            name='codice',
            field=models.CharField(blank=True, help_text='Da ART.DBF colonna APR050 (solo import, non modificabile a mano)', max_length=50, null=True, unique=True, verbose_name='Codice fornitore'),
        ),
        migrations.AlterField(
            model_name='fornitore',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
