# Generated by Django 6.0.1 on 2026-01-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VenditaStorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=50)),
                ('data_vendita', models.DateField(db_index=True)),
                ('quantita', models.DecimalField(decimal_places=3, max_digits=10)),
                ('anno_riferimento', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['sku', 'data_vendita'], name='sales_vendi_sku_355826_idx')],
            },
        ),
    ]
