# Generated by Django 6.0.1 on 2026-02-02 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_prodotto_pezzi_per_cartone'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquistoStorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('quantita', models.DecimalField(decimal_places=2, max_digits=10)),
                ('riferimento', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Acquisti Storici',
            },
        ),
        migrations.AlterModelOptions(
            name='venditastorica',
            options={'verbose_name_plural': 'Vendite Storiche'},
        ),
        migrations.RemoveIndex(
            model_name='venditastorica',
            name='sales_vendi_sku_355826_idx',
        ),
        migrations.RenameField(
            model_name='venditastorica',
            old_name='data_vendita',
            new_name='data',
        ),
        migrations.AddField(
            model_name='venditastorica',
            name='prodotto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendite', to='inventory.prodotto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venditastorica',
            name='riferimento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venditastorica',
            name='quantita',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='venditastorica',
            index=models.Index(fields=['prodotto', 'data'], name='sales_vendi_prodott_4aa15f_idx'),
        ),
        migrations.AddField(
            model_name='acquistostorico',
            name='prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisti', to='inventory.prodotto'),
        ),
        migrations.RemoveField(
            model_name='venditastorica',
            name='anno_riferimento',
        ),
        migrations.RemoveField(
            model_name='venditastorica',
            name='sku',
        ),
        migrations.AddIndex(
            model_name='acquistostorico',
            index=models.Index(fields=['prodotto', 'data'], name='sales_acqui_prodott_5bacbc_idx'),
        ),
    ]
